services:
  - type: web
    name: zlpix-backend
    env: node
    region: oregon
    rootDir: backend
    buildCommand: |
      echo "🧹 Limpando migrações antigas..."
      rm -rf prisma/migrations

      echo "🧩 Sincronizando schema Prisma com o banco existente..."
      npx prisma db push --accept-data-loss
      npx prisma generate

      echo "📦 Instalando dependências e buildando projeto..."
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.16.0