services:
  - type: web
    name: zlpix-backend
    env: node
    rootDir: .
    plan: free

    buildCommand: |
      npm ci
      npx prisma generate
      npm run build

    startCommand: |
      npm start

    envVars:
      - key: DATABASE_URL
        sync: false

      - key: JWT_SECRET
        sync: false

      - key: NODE_VERSION
        value: 18.20.2

      - key: PORT
        value: 10000

    autoDeploy: true
    branch: main
